apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "banking-app.fullname" . }}-db-migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for DB..."
              until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"; do
                sleep 5
              done

              echo "Running schema migration..."
              mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /scripts/schema.sql

              echo "Running seed data..."
              mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /scripts/sample-data.sql

              echo "DB migration completed"
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretName }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ .Values.db.migrationConfigMap }}
