apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
type: Opaque
data:
  RDS_HOST: {{ .Values.rds.host | b64enc }}
  RDS_USERNAME: {{ .Values.rds.username | b64enc }}
  RDS_PASSWORD: {{ .Values.rds.password | b64enc }}
  RDS_DBNAME: {{ .Values.rds.dbname | b64enc }}