apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  host: {{ .Values.rds.host | b64enc }}
  username: {{ .Values.rds.username | b64enc }}
  password: {{ .Values.rds.password | b64enc }}
  dbname: {{ .Values.rds.dbname | b64enc }}