apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
