apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
