replicaCount: 2

image:
  backend:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/3tierbanking-app
    tag: backend
    pullPolicy: Always
  frontend:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/3tierbanking-app
    tag: frontend
    pullPolicy: Always

service:
  type: LoadBalancer
  backend:
    port: 8080
  frontend:
    port: 80

db:
  secretName: rds-secret
  migrationConfigMap: db-migration-configmap

rds:
  host: banking-mysql.ctek4ma6atd4.ap-south-1.rds.amazonaws.com
  username: dbuser
  password: soumya987
  dbname: bankingdb

ingress:
  enabled: false